import Styles from "./layout.module.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function mainLayout({ children }) {
  return (
    <div className={Styles.layoutRoot}>
      <div className={Styles.layoutHeader}>
        <img src="/assets/logos/logo-rui.png" alt="rui-logo"></img>
      </div>
      <div className={Styles.layoutBody}>
        {children}
      </div>
      <div className={Styles.layoutFooter}>
        <p>Desarrollado por</p>
        <img src="/assets/logos/logo-argos.png" alt="argos-logo"></img>
      </div>
    </div>
  );
};